name: nn4dms
dependencies:
  - python=3.6.12
  - numpy=1.16.4
  - pandas=1.1.1
  - scipy=1.5.2
  - scikit-learn=0.23.2
  - tensorflow=1.14
  - gast=0.2.2
  - networkx=2.5
  - tqdm=4.48.2
  - pyyaml=5.3.1
  - matplotlib=3.3.1
  - seaborn=0.10.1
  - pyyaml=5.3.1
  - absl-py=0.15.0
  - conda-forge::biopandas=0.2.7
  - conda-forge::shortuuid=1.0.1
  - conda-forge::umap-learn=0.4.0
  - conda-forge::pynndescent=0.4.8
  - conda-forge::jupyterlab=2.2.8